server:
  port: 5000
  servlet:
    context-path: /stems
    session:
      cookie:
        name: UISESSION
security:
  oauth2:
    sso:
      login-path: /login
    client:
      accessTokenUri: http://localhost:8080/oauth/token
      userAuthorizationUri: http://localhost:8080/oauth/authorize
      authorized-grant-types:
      - code      
      pre-established-redirect-uri: http://localhost:5000/stems/
      registered-redirect-uri:
      - http://localhost:5000/stems/
      use-current-uri: false
      clientId: stems_app
      client-secret: stems_secret
    resource:
      user-info-uri: http://localhost:8080/me
spring:
  security:
    user:
      password: none  
  aop:
    proxy-target-class: true
zuul:
  #add-proxy-headers: true
  routes:
    resource:
      path: /api/**
      url: http://localhost:8081/um-webapp-resource-server/
      sensitive-headers:
      - Authorization
      strip-prefix: false
       