server:
  port: 8081
  servlet:
    context-path: /resource
spring:
  security:
    user:
      password: password    
security:
  oauth2:
   resource:
      user-info-uri: http://localhost:8080/uaa/user